import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String currentLanguageCode = 'en';

  Locale get locale => Locale(currentLanguageCode);

  void changeLanguage(String code) {
    currentLanguageCode = code;
    notifyListeners();
  }

  String tr(String key) {
    final data = {
      'en': {
        'appName': 'Spend Summary',
        'loginTitle': 'Welcome to Spend Summary',
        'loginSubtitle': 'Login to view your monthly spend, category insights and recent transactions.',
        'emailMobile': 'Email / Mobile Number',
        'password': 'Password',
        'secureLogin': 'Secure Login',
        'signup': 'Sign Up',
        'newTenant': 'New user? Create account',
        'createAccount': 'Create a Spend Summary account',
        'dashboard': 'Dashboard',
        'payRent': 'Add Expense',
        'bills': 'Summary',
        'tickets': 'Transactions',
        'profile': 'Profile',
        'documents': 'Reports',
        'myDocs': 'Reports',
        'settings': 'Settings',
        'alerts': 'Spend Alerts',
        'contactUs': 'Contact Us',
        'faqs': 'FAQs',
        'logout': 'Logout',
        'language': 'Language',
        'theme': 'Theme',
        'submitTicket': 'Add Transaction',
        'editProfile': 'Edit Profile',
        'save': 'Save',
        'downloaded': 'Report downloaded successfully',
        'ticketSubmitted': 'Transaction added successfully',
        'paymentSuccess': 'Expense submitted successfully',
        'profileUpdated': 'Profile updated successfully',
        'signupSuccess': 'Signup successful',
      },
      'hi': {
        'appName': 'Spend Summary',
        'loginTitle': 'स्वागत है',
        'loginSubtitle': 'अपने मासिक खर्च और लेन-देन आसानी से देखें।',
        'emailMobile': 'ईमेल / मोबाइल नंबर',
        'password': 'पासवर्ड',
        'secureLogin': 'सुरक्षित लॉगिन',
        'signup': 'साइन अप',
        'newTenant': 'नया यूज़र? खाता बनाएं',
        'createAccount': 'Spend Summary खाता बनाएं',
        'dashboard': 'डैशबोर्ड',
        'payRent': 'खर्च जोड़ें',
        'bills': 'सारांश',
        'tickets': 'लेन-देन',
        'profile': 'प्रोफाइल',
        'documents': 'रिपोर्ट',
        'myDocs': 'रिपोर्ट',
        'settings': 'सेटिंग्स',
        'alerts': 'खर्च अलर्ट',
        'contactUs': 'संपर्क करें',
        'faqs': 'सामान्य प्रश्न',
        'logout': 'लॉगआउट',
        'language': 'भाषा',
        'theme': 'थीम',
        'submitTicket': 'लेन-देन जोड़ें',
        'editProfile': 'प्रोफाइल संपादित करें',
        'save': 'सेव',
        'downloaded': 'रिपोर्ट डाउनलोड हुई',
        'ticketSubmitted': 'लेन-देन सफलतापूर्वक जोड़ा गया',
        'paymentSuccess': 'खर्च सफलतापूर्वक जोड़ा गया',
        'profileUpdated': 'प्रोफाइल अपडेट हुई',
        'signupSuccess': 'साइनअप सफल',
      },
      'mr': {
        'appName': 'Spend Summary',
        'loginTitle': 'स्वागत आहे',
        'loginSubtitle': 'मासिक खर्च आणि व्यवहार सहज ट्रॅक करा.',
        'emailMobile': 'ईमेल / मोबाइल नंबर',
        'password': 'पासवर्ड',
        'secureLogin': 'सुरक्षित लॉगिन',
        'signup': 'साइन अप',
        'newTenant': 'नवीन यूज़र? खाते तयार करा',
        'createAccount': 'Spend Summary खाते तयार करा',
        'dashboard': 'डॅशबोर्ड',
        'payRent': 'खर्च जोडा',
        'bills': 'सारांश',
        'tickets': 'व्यवहार',
        'profile': 'प्रोफाइल',
        'documents': 'रिपोर्ट',
        'myDocs': 'रिपोर्ट',
        'settings': 'सेटिंग्स',
        'alerts': 'खर्च सूचना',
        'contactUs': 'संपर्क',
        'faqs': 'सामान्य प्रश्न',
        'logout': 'लॉगआउट',
        'language': 'भाषा',
        'theme': 'थीम',
        'submitTicket': 'व्यवहार जोडा',
        'editProfile': 'प्रोफाइल बदला',
        'save': 'सेव्ह',
        'downloaded': 'रिपोर्ट डाउनलोड झाली',
        'ticketSubmitted': 'व्यवहार यशस्वीरित्या जोडला',
        'paymentSuccess': 'खर्च यशस्वीरित्या जोडला',
        'profileUpdated': 'प्रोफाइल अपडेट झाले',
        'signupSuccess': 'साइनअप यशस्वी',
      },
    };
    return data[currentLanguageCode]?[key] ?? data['en']![key] ?? key;
  }
}
